
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bebra
      POSTGRES_DB: fittest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    env_file: .env
    build: .
    container_name: fastapi_backend
    restart: always

  nginx:
    build: ./nginx
    container_name: fastapi_nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend

volumes:
  postgres_data: