
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: fastapi_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: