version: '3.8'

services:
  backend:
    build: .
    container_name: fastapi_backend
    restart: always

  nginx:
    build: ./nginx
    container_name: fastapi_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend