"""add mean and deviation into category

Revision ID: dcc9b503fe0e
Revises: e14be7afdbaf
Create Date: 2025-07-16 21:56:17.698608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc9b503fe0e'
down_revision: Union[str, None] = 'e14be7afdbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('mean', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('deviation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deviation')
    op.drop_column('categories', 'mean')
    # ### end Alembic commands ###
